#!/usr/bin/env python3
"""Builds public/molly-francis-resume-ats.pdf — the plain, parser-friendly
résumé that sits beside the designed one.

Why a script: the ATS file used to be regenerated by hand, so its copy drifted
from the designed PDF. Everything it says lives in CONTENT below; edit that and
re-run. Liberation Sans is metric-compatible with Arial, which is what ATS
parsers expect, and every line is real text — no images, no columns, no tables.

    python3 scripts/build-ats-resume.py
"""
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

FONT_DIR = "/usr/share/fonts/truetype/liberation"
OUT = "public/molly-francis-resume-ats.pdf"

NAME = "Molly Francis"
TAGLINE = "Building cool products in Austin, Texas"
# Same five contact points as the designed PDF, in the same order. Spelled as
# full URLs rather than the designed file's "Dribbble" / "Instagram" labels:
# a parser stores what it reads, so the address has to be the text.
CONTACT = [
    "mollyfrancis.com",
    "linkedin.com/in/molly-francis-89041515",
    "dribbble.com/mollyfrancis",
    "instagram.com/moshofra",
    "yo@mollyfrancis.com",
]

EXPERIENCE = [
    ("Lead Product Designer — Netspend", "November 2025 — Current", [
        "Own design strategy and end-to-end UX for Netspend's Rewards program — the consumer-facing app and the internal Unified Commerce Management (UCM) tool that powers it.",
        "Reworked the rewards layout and Information Architecture around new UCM capabilities.",
        "Run qualitative and quantitative user testing to validate decisions and guide iteration.",
        "Use AI-assisted workflows (Claude, Claude Cowork, Gemini, Cursor, Figma Make) to accelerate design exploration, prototyping, and iteration speed.",
    ]),
    ("Lead Product Designer — GovOS (Neumo)", "October 2023 — October 2025", [
        "Drive UX strategy and design execution across core GovOS products, including eSubmission, Business Licensing & Tax, Cloud Search, and Cloud Records.",
        "Conduct and synthesize user research to uncover insights, validate solutions, and guide product decisions.",
        "Partner with cross-functional teams and executive stakeholders to align user needs with business goals, driving go-to-market decisions for complex government workflows.",
        "Lead design systems governance, accessibility, and DesignOps initiatives to ensure long-term product growth and meaningful public impact.",
        "Designed to Section 508 / WCAG standards so products could carry a VPAT for public-sector procurement.",
        "Piloted AI-assisted design and prototyping workflows (ChatGPT) to accelerate iteration and validate solutions faster across GovOS products.",
    ]),
    ("Principal Product Designer — Bright Health", "March 2021 — April 2023", [
        "Established a 0 to 1 provider portal for Prior Authorizations, reducing manual paperwork and enabling providers to electronically submit and track authorization status in real time.",
        "Conducted user research and usability testing to validate workflows, uncover pain points, and ensure solutions met provider and patient needs.",
        "Provided design leadership and mentorship, managing two designers and co-creating and governing a design system at a WCAG 2.2 AA accessibility standard that improved consistency and accelerated delivery across multiple products.",
        "Designed a telehealth app (desktop + native mobile) that expanded patient access to care by supporting asynchronous / synchronous urgent visits and prescription refills.",
    ]),
    ("Principal Product Designer — Care.com (HomePay)", "April 2020 — February 2021", [
        "Led the HomePay design team for a payroll, tax, and HR solution serving families with household employees (nannies, senior caregivers, etc.).",
        "Partnered with executive leadership to integrate UX into agile workflows, aligning design with product strategy and business goals.",
        "Managed and scaled the UX team — mentoring designers, facilitating critique, and building a stronger design culture to elevate quality and collaboration.",
        "Designed and enhanced internal Sales tools and client / employee-facing HomePay products, improving efficiency and user experience.",
    ]),
    ("Lead UX Designer — Liveperson", "July 2019 — February 2020", [
        "Served as lead designer on a new social media management product, enabling brands to interact with consumers over social platforms through the LiveEngage AI-powered messaging product.",
        "Collaborated with the global UX team to update and scale the company's design system for AI and chatbot products, improving accessibility and consistency company-wide.",
    ]),
    ("Principal Product Designer — athenahealth", "September 2016 — June 2019", [
        "Conducted research and design for desktop and native mobile electronic health record (EHR) and patient portal products, improving usability and adoption for clinicians and patients.",
        "Collaborated with a multi-disciplinary agile R&D team to define, design, and test features, streamlining workflows and enhancing the overall user experience.",
        "Led user testing and validation, identifying pain points and driving design improvements that increased efficiency, reduced errors, and elevated patient satisfaction.",
    ]),
    ("Lead Product Designer — Patient IO", "July 2016 — August 2016", [
        "Served as Head of Product Design for desktop and native mobile apps supporting at-risk patients, designing for both patient-facing users and care managers.",
        "Worked in a lean, iterative environment, streamlining designs and eliminating waste while accelerating delivery.",
        "Collaborated with cross-functional teams to align design with product strategy and operational goals.",
        "Maintained a customer-centric perspective, ensuring design decisions prioritized patient needs and improved care outcomes.",
    ]),
    ("Senior UX Designer — Volusion / Mozu", "September 2014 — June 2016", [
        "Designed interaction flows, visual design, and user experiences for the Volusion and Mozu e-commerce platforms.",
        "Improved usability and engagement by refining UX flows and ensuring consistent visual design across the platforms.",
    ]),
]
EXPERIENCE_NOTE = "See more experiences on linkedin.com/mollyfrancisdesign."

SKILLS = [
    ("Leadership & Strategy", "Product Vision, Design Strategy & Roadmap, Design Operations (DesignOps), Design Systems Governance, ROI of Design"),
    ("Stakeholder & Business Alignment", "Cross-Functional Leadership, Executive Stakeholder Management, Go-to-Market Strategy, Change Management, Business Metrics Alignment"),
    ("Mentorship & Team Growth", "Design Mentorship, Talent Development, Team Building, Critique Facilitation, Design Culture"),
    ("Execution & Craft", "User Research, Complex Problem Solving, Service Design, Information Architecture, Interaction Design, Accessibility (WCAG 2.2 AA), Design Tokens & Component Libraries, Agile / Scrum Workflows, Prototyping, Storytelling, Workshop Facilitation"),
    ("Data & Validation", "Product Analytics, A/B Testing, Quantitative Research, Qualitative Validation, Cohort Analysis, KPIs & Business Metrics, Usability Testing"),
]
PROGRAMS = ("Figma, UserBit, Pendo, Adobe CC, Miro, Optimal Workshop, Usertesting.com, Dovetail, "
            "Jira, Asana, Slack, HTML, CSS, Claude, Claude Cowork, ChatGPT, Cursor, GitHub, Vercel, "
            "Lovable, Notion, Amazon QuickSight")
SCHOOL = "Oklahoma State University — Bachelor of Fine Arts in Graphic Design"
RECOGNITION = [
    "RecruitLoop — Top 50 Female UI/UX Designers — Austin, Texas",
    "Built In ATX — Featured Employee at Bright Health — Austin, Texas",
]

# ── layout ───────────────────────────────────────────────────────────────
W, H = letter
M = 0.75 * inch
BODY, LEAD = 9.5, 12.6

pdfmetrics.registerFont(TTFont("Lib", f"{FONT_DIR}/LiberationSans-Regular.ttf"))
pdfmetrics.registerFont(TTFont("Lib-B", f"{FONT_DIR}/LiberationSans-Bold.ttf"))

c = canvas.Canvas(OUT, pagesize=letter)
c.setTitle("Molly Francis — Résumé (ATS)")
c.setAuthor(NAME)
y = H - M

def room(need):
    global y
    if y - need < M:
        c.showPage(); y = H - M

def wrap(text, font, size, width):
    words, lines, line = text.split(), [], ""
    for w in words:
        trial = f"{line} {w}".strip()
        if pdfmetrics.stringWidth(trial, font, size) <= width:
            line = trial
        else:
            lines.append(line); line = w
    if line: lines.append(line)
    return lines

def para(text, font="Lib", size=BODY, indent=0, gap=0):
    global y
    for ln in wrap(text, font, size, W - 2*M - indent):
        room(LEAD)
        c.setFont(font, size); c.drawString(M + indent, y, ln); y -= LEAD
    y -= gap

def bullet(text):
    global y
    lines = wrap(text, "Lib", BODY, W - 2*M - 14)
    for i, ln in enumerate(lines):
        room(LEAD)
        c.setFont("Lib", BODY)
        if i == 0: c.drawString(M, y, "•")
        c.drawString(M + 14, y, ln); y -= LEAD

def section(title):
    global y
    room(34); y -= 8
    c.setFont("Lib-B", 10.5); c.drawString(M, y, title.upper()); y -= 6
    c.setLineWidth(0.6); c.line(M, y, W - M, y); y -= 14

# header
c.setFont("Lib-B", 19); c.drawString(M, y, NAME); y -= 22
c.setFont("Lib", BODY + 1); c.drawString(M, y, TAGLINE); y -= 15
para(" | ".join(CONTACT), size=BODY, gap=4)

section("Experience")
for role, dates, bullets in EXPERIENCE:
    room(40)
    c.setFont("Lib-B", BODY + 1); c.drawString(M, y, role); y -= LEAD
    c.setFont("Lib", BODY); c.drawString(M, y, dates); y -= LEAD
    for b in bullets: bullet(b)
    y -= 8
para(EXPERIENCE_NOTE, gap=2)

section("Skills")
for label, items in SKILLS:
    para(f"{label}: {items}", gap=4)

section("Programs")
para(PROGRAMS)

section("School & Recognition")
para(SCHOOL, gap=2)
for r in RECOGNITION: bullet(r)

c.save()
print("wrote", OUT)
